Vet clinic Database project module four.
juaryimami/rupby-project pull request #1
Opened 2023-01-16 19:43 UTC by juaryimami

### In this project,
---
- I use a relational database to create the initial data structure for a vet clinic.
-  I also create a table to store animals' information, insert some data into it, and query it.
- I have attached the screenshot of all of my sql query as shown below.
![Screenshot from 2023-01-16 18-15-11](https://user-images.githubusercontent.com/49280606/212754856-8068e42a-9b4d-4f2a-a2d0-105d9781cf25.png)
![Screenshot from 2023-01-16 18-16-43](https://user-images.githubusercontent.com/49280606/212754865-df4d0ac3-8064-43f4-8089-62d6c0d263c1.png)
![Screenshot from 2023-01-16 18-17-14](https://user-images.githubusercontent.com/49280606/212754867-5d82f9bf-5f81-4ce4-bf7d-189ad7dde13e.png)
![Screenshot from 2023-01-16 21-55-33](https://user-images.githubusercontent.com/49280606/212754868-5309033a-e332-4ab4-9b1a-79e7270cae0f.png)
![Screenshot from 2023-01-16 22-00-11](https://user-images.githubusercontent.com/49280606/212754870-1d63b564-bf93-4df9-8313-09e29cd00568.png)
![Screenshot from 2023-01-16 22-05-48](https://user-images.githubusercontent.com/49280606/212754873-00ac94b8-5c38-42e4-8fa4-29df85da996f.png)
![Screenshot from 2023-01-16 22-08-42](https://user-images.githubusercontent.com/49280606/212754878-d69546b7-5374-4e52-8d12-59ce91125919.png)
![Screenshot from 2023-01-16 22-16-01](https://user-images.githubusercontent.com/49280606/212754880-e7cd6c79-ac27-4ac6-a425-e5a8893abfd5.png)
![Screenshot from 2023-01-16 22-20-30](https://user-images.githubusercontent.com/49280606/212754882-fac0a2e5-3aaa-4121-a5ed-2ef4a0cb44f0.png)
---
#### Thank you for reviewing my project!!!!.

2023-01-16 20:21 UTC, BenMukebo requested changes
### Hi @juaryimami,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Gitflow was correctly used.  ✔️   
- Professional README ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [ ]  Please consider updating the screenshots of your queries results to the pull request description. This also helps to ensure that you run the queries with success.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 20:21 UTC, BenMukebo commented on queries.sql
> +SELECT name from animals WHERE date_of_birth BETWEEN '2016-01-01' and '2019-01-01';
- [ ] For this requirement, ` list the name of all animals born between 2016 and 2019.` Here you should list the name of all animals starting from the first day of the first month of 2016 up to the last day of the last month of 2019, hope this makes sense 🤔 Your code might look like this:

```sql
SELECT name FROM animals WHERE date_of_birth >= '2016/01/01' AND date_of_birth <= '2019/31/12';
# 0r 
SELECT name FROM animals WHERE EXTRACT(year FROM date_of_birth) BETWEEN 2016 AND 2019;
```


- Please correct this 👍🏻

2023-01-16 20:21 UTC, BenMukebo commented on queries.sql
> +SELECT name from animals where escape_attempts <3;
- [ ] For this one, `list the name of all animals that are neutered and have less than 3 escape attempts.` You are missing adding conditions for the `neutered` case. kindly add this. Your code might look like this:

```sql
SELECT name FROM animals WHERE neutered = 'true' AND escape_attempts < '3';
```

2023-01-16 20:21 UTC, BenMukebo commented on queries.sql
> +SELECT name, escape_attempts from animals where weight_kg >10;
- [ ] Let's be more consistent 🥲 `list name and escape attempts of animals that weigh more than 10.5kg` as you can see, it is 10.5 and not 10. Please correct this 👍🏻 

```sql
SELECT name, escape_attempts FROM animals WHERE weight_kg > '10.5';
```

2023-01-17 05:49 UTC, juaryimami commented
Ok thanks sir!

On Mon, 16 Jan 2023, 11:21 pm Kasongo Mukebo Ben, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @juaryimami <https://github.com/juaryimami>,
>
> You did a great job so far 👏🏼 👏🏼
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> To highlight 💪🏻
>
>    - Gitflow was correctly used. ✔️
>    - Professional README ✔️
>    👍 Good job!
>
> STATUS: CHANGES REQUESTED ♻️
>
> *Please Check the comments under the review and make all required changes*
>
>    - Please consider updating the screenshots of your queries results to
>    the pull request description. This also helps to ensure that you run the
>    queries with success.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏 💻
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please ping me @BenMukebo <https://github.com/BenMukebo> when you comment
> so I can receive the notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In queries.sql
> <https://github.com/juaryimami/rupby-project/pull/1#discussion_r1071555516>
> :
>
> > @@ -1,3 +1,10 @@
>
>  /*Queries that provide answers to the questions from all projects.*/
>
> -
>
> -SELECT * from animals WHERE name = 'Luna';
>
> +SELECT * from animals;
>
> +SELECT * from animals where name like '%mon';
>
> +SELECT name from animals WHERE date_of_birth BETWEEN '2016-01-01' and '2019-01-01';
>
>
>
>    - For this requirement, list the name of all animals born between 2016
>    and 2019. Here you should list the name of all animals starting from
>    the first day of the first month of 2016 up to the last day of the last
>    month of 2019, hope this makes sense 🤔 Your code might look like this:
>
> SELECT name FROM animals WHERE date_of_birth >= '2016/01/01' AND date_of_birth <= '2019/31/12';
> # 0r
> SELECT name FROM animals WHERE EXTRACT(year FROM date_of_birth) BETWEEN 2016 AND 2019;
>
>
>    - Please correct this 👍🏻
>
> ------------------------------
>
> In queries.sql
> <https://github.com/juaryimami/rupby-project/pull/1#discussion_r1071557037>
> :
>
> > @@ -1,3 +1,10 @@
>
>  /*Queries that provide answers to the questions from all projects.*/
>
> -
>
> -SELECT * from animals WHERE name = 'Luna';
>
> +SELECT * from animals;
>
> +SELECT * from animals where name like '%mon';
>
> +SELECT name from animals WHERE date_of_birth BETWEEN '2016-01-01' and '2019-01-01';
>
> +SELECT name from animals where escape_attempts <3;
>
>
>
>    - For this one, list the name of all animals that are neutered and
>    have less than 3 escape attempts. You are missing adding conditions
>    for the neutered case. kindly add this. Your code might look like this:
>
> SELECT name FROM animals WHERE neutered = 'true' AND escape_attempts < '3';
>
> ------------------------------
>
> In queries.sql
> <https://github.com/juaryimami/rupby-project/pull/1#discussion_r1071558588>
> :
>
> > @@ -1,3 +1,10 @@
>
>  /*Queries that provide answers to the questions from all projects.*/
>
> -
>
> -SELECT * from animals WHERE name = 'Luna';
>
> +SELECT * from animals;
>
> +SELECT * from animals where name like '%mon';
>
> +SELECT name from animals WHERE date_of_birth BETWEEN '2016-01-01' and '2019-01-01';
>
> +SELECT name from animals where escape_attempts <3;
>
> +SELECT date_of_birth from animals where name = 'Agumon' or  name = 'Pikachu';
>
> +SELECT name, escape_attempts from animals where weight_kg >10;
>
>
>
>    - Let's be more consistent 🥲 list name and escape attempts of animals
>    that weigh more than 10.5kg as you can see, it is 10.5 and not 10.
>    Please correct this 👍🏻
>
> SELECT name, escape_attempts FROM animals WHERE weight_kg > '10.5';
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/juaryimami/rupby-project/pull/1#pullrequestreview-1250629988>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALX7MXVRTOPIDGEMV3MMSCDWSWUVHANCNFSM6AAAAAAT5CXTJM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-17 06:09 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @juaryimami  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:
- Made changes as requested by reviewer.
- 
## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-17 06:10 UTC, juaryimami commented
Thank you!

On Tue, 17 Jan 2023, 9:09 am Mumenya Nyamu, ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> STATUS: APPROVED ✔️ 🟢
>
> Hi @juaryimami <https://github.com/juaryimami> 😄 ,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
>
> <https://camo.githubusercontent.com/23cd37b47db75464ac75a4facb8b438a63ce35ea5cac0abf9bcf89e6ce540ab6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c347137544957386e455a594f4a5566362f67697068792e676966>
> Highlights ✨
>
>    - Made changes as requested by reviewer.
>    -
>
> Optional suggestions ☑️
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> APPROVED! 💯 💯 💯
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me, @Nyame-Wolf <https://github.com/Nyame-Wolf>
> in your question so I can receive the notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/juaryimami/rupby-project/pull/1#pullrequestreview-1250927828>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALX7MXVXXEJSWICGRWUHNPTWSYZSHANCNFSM6AAAAAAT5CXTJM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-18 07:39 UTC, merged

2023-03-27 07:50 UTC, omarsalem7 commented
Hi 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._